# TmSetup - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: Ensure the PostgreSQL service is running
  become: yes
  service: name=postgresql state=started enabled=yes
  tags:
    - database

- name: Create database
  become: yes
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_db: name={{ db_name }}
  tags:
    - database

- name: Init postgis extension
  become: yes
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  shell: "echo 'CREATE EXTENSION postgis;' | psql tissuemaps "
  args:
    executable: /bin/bash
  tags:
    - database

