---
- name: Create pgpass file
  template:
    src=pgpass.j2
    dest={{ ansible_env.HOME }}/.pgpass
    group={{ deploy_user }}
    owner={{ deploy_user }}
    mode=600
    # mode="u=rw"
  tags:
    - db

- name: Place script for recreating the database
  template: src=resetdb.sql.j2 dest={{ ansible_env.HOME }}/resetdb.sql
  tags:
    - db

- name: Update db password to TissueMAPS configuration
  ini_file:
    dest={{ tmaps_config_file }}
    section=DEFAULT
    state=present
    option=db_password
    value={{ db_password }}
  tags:
    - db
    - tissuemaps

- name: Change db host in TissueMAPS configuration
  ini_file:
    dest={{ tmaps_config_file }}
    section=DEFAULT
    state=present
    option=db_host
    value={{ db_host }}
  tags:
    - db
    - tissuemaps
