---
- name: Drop sysadmin SSH keys and ensure they are authorized for `root` user
  become: yes
  authorized_key: user=root key=https://github.com/{{ item }}.keys
  with_items: {{ tm_admins }}
  tags:
    - ssh

- name: Drop SSH keys of authorized users
  become: yes
  authorized_key: user={{ deploy_user }} key=https://github.com/{{ item }}.keys
  with_items: {{ tm_users }}
  tags:
    - ssh

