---
- name: Clone TmServer repository
  git:
    repo={{ tm_github_url }}/tmserver
    dest={{ ansible_env.HOME }}/tmserver
    version={{ tmserver_branch }}
  tags:
    - tissuemaps

- name: Install tmserver package
  shell: pip install -e {{ ansible_env.HOME }}/tmserver --user --process-dependency-links
  args:
    chdir={{ ansible_env.HOME }}/tmserver
    executable=/bin/bash
  tags:
    - tissuemaps

# - name: Install tmserver package
#   pip:
#     name: "git+{{ tm_github_url }}/tmserver@{{ tmserver_branch }}#egg=tmserver"
#     extra_args: "--user --process-dependency-links"
#   tags:
#     - tissuemaps
#     - tmserver

- name: Add server config to TissuMAPS configuration file
  command: "{{ tmaps_install_location }}/tm_create_config --server"
  tags:
    - tissuemaps
    - tmserver
