---
- name: Install apt packages
  sudo: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - nodejs
    # - npm
  tags:
    - tissuemaps
    - client
    - web

# - name: Corrections for nodejs
#   sudo: yes
#   file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
#   tags:
#     - tmserver
#     - web

- name: Install npm packages
  sudo: yes
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  with_items:
    - bower
    - gulp
  tags:
    - tissuemaps
    - client
    - web

- name: Delete tmui folder
  sudo: yes
  file: path="{{ deploy_home_folder }}/tmui" state=absent
  tags:
    - git
    - tissuemaps
    - client
    - web

- name: Get the latest tmui code
  shell: "git clone --recursive {{ tm_github_url }}/tmui {{ deploy_home_folder }}/tmui && cd {{ deploy_home_folder }}/tmui && git checkout {{ tmui_branch }}"
  tags:
    - git
    - tissuemaps
    - client
    - web

- name: Get submodules of tissuemaps client code
  shell: "cd {{ deploy_home_folder }}/tmclient && git submodule update --recursive --init && git submodule foreach 'git checkout master'"
  tags:
    - git
    - tissuemaps
    - client
    - web

- name: Update npm
  sudo: yes
  shell: npm install npm -g
  tags:
    - web
    - tissuemaps
    - client

- name: Install npm files
  shell: source {{ deploy_home_folder }}/.tmapsrc.sh && npm install
  args:
    executable: /bin/bash
    chdir: "{{ deploy_home_folder }}/tmclient/src/javascript"
  tags:
    - web
    - tissuemaps
    - client

# Patch private git url in bower.json
# - name: Patch bower files
#   lineinfile:
#     dest: "{{ deploy_home_folder }}/tmclient/src/bower.json"
#     state: present
#     regexp: '^.*/TmAuth.git\"'
#     line: '    "tmauth": \"{{ tmaps_git_url }}/TmAuth.git"'

- name: Install bower files
  shell: source {{ deploy_home_folder }}/.tmapsrc.sh && bower install
  args:
    executable: /bin/bash
    chdir: "{{ deploy_home_folder }}/tmclient/src/javascript"
  tags:
    - web

- name: Build gulp dist
  shell: source {{ deploy_home_folder }}/.tmapsrc.sh && gulp build --prod
  args:
    executable: /bin/bash
    chdir: "{{ deploy_home_folder }}/tmclient/src/javascript"
  tags:
    - web
