---
- name: Install apt packages
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - nodejs
    - npm
  tags:
    - tissuemaps
    - client
    - web

- name: Corrections for nodejs
  become: yes
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  tags:
    - tmserver
    - web

# - name: Install npm packages
#   become: yes
#   npm: name={{ item }} state=present global=yes
#   with_items:
#     - bower
#     - gulp
#   tags:
#     - tissuemaps
#     - client
#     - web

- name: Get the latest tmui code
  git: repo={{ tm_github_url }}/tmui version={{ tmui_branch }} recursive=yes dest={{ deploy_home_folder }}/tmui
  tags:
    - tissuemaps
    - client
    - web

- name: Update npm
  become: yes
  command: npm install npm -g
  tags:
    - web
    - tissuemaps
    - client

- name: Install npm dependencies
  npm: path={{ deploy_home_folder }}/tmui/src/app state=present
  tags:
    - web
    - tissuemaps
    - client

# Patch private git url in bower.json
# - name: Patch bower files
#   lineinfile:
#     dest: "{{ deploy_home_folder }}/tmclient/src/bower.json"
#     state: present
#     regexp: '^.*/TmAuth.git\"'
#     line: '    "tmauth": \"{{ tmaps_git_url }}/TmAuth.git"'

- name: Install bower dependencies
  bower: path={{ deploy_home_folder }}/tmui/src/app state=present
  tags:
    - web
    - tissuemaps
    - client

- name: Build client code for production deployment
  shell: gulp build --prod
  args:
    executable: /bin/bash
    chdir: "{{ deploy_home_folder }}/tmui/src"
  tags:
    - web
    - tissuemaps
    - client
