---
- name: Install tmserver package
  pip:
    name: "git+{{ tm_github_url }}/tmserver@{{ tmserver_branch }}#egg=tmserver"
    extra_args: "--user --process-dependency-links"
  tags:
    - tissuemaps
    - tmserver

# - name: Remove existing TissuMAPS configuration files
#   file: path={{ tmaps_config_file }} state=absent

- name: Add server config to TissuMAPS configuration file
  command: "{{ tmaps_install_location }}/tm_create_config --server"
  tags:
    - tissuemaps
    - tmserver
