# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
- name: Add user group
  become: yes
  group:
    name: "{{ item }}"
  with_items:
    - "{{ tm_group }}"
    - "{{ db_group }}"

- name: Add user
  become: yes
  user:
    name: "{{ item['user'] }}"
    shell: /bin/bash
    group: "{{ item['group'] }}"
    append: yes
    createhome: yes
    home: /home/{{ item['user'] }}
  with_items:
    - group: "{{ tm_group }}"
      user: "{{ tm_user }}"
    - group: "{{ db_group }}"
      user: "{{ db_user }}"

- name: Change permissions for user home directory
  become: yes
  file:
    path: /home/{{ item }}
    state: directory
    mode: 0775
  with_items:
    - "{{ tm_user }}"
    - "{{ db_user }}"

- name: Add tm_user to sudoers
  become: yes
  lineinfile:
    dest: /etc/sudoers.d/{{ tm_user }}
    # TODO: Make sudo rights more restrictive
    regexp: "{{ tm_user }} ALL=(ALL) NOPASSWD:ALL"
    line: "{{ tm_user }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    create: yes

- name: Create SSH directory for tm_user
  become: yes
  file:
    path: "{{ tm_home }}/.ssh"
    state: directory
    recurse: yes
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
    mode: 0700

- name: Enable SSH access for tm_user
  become: yes
  copy:
    src: /home/{{ ansible_user }}/.ssh/authorized_keys
    remote_src: yes
    dest: "{{ tm_home }}/.ssh/authorized_keys"
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
    mode: 0700
