
# Configuration of image preprocessing and pyramid creation based on the
# project layout, i.e. folder structure and file name nomenclature.


# How to convert filenames into site numbers (coordinates)
COORDINATE_FROM_FILENAME: '_r(\d+)_c(\d+)_'
COORDINATES_IN_FILENAME_ONE_BASED: Yes

# Where the shift descriptors are, `cycle_subdirectory` should have the
# format given below.
SHIFT_FOLDER_LOCATION: '{cycle_subdirectory}/ALIGNCYCLES'
SHIFT_DESCRIPTOR_FILE_LOCATION: '{cycle_subdirectory}/ALIGNCYCLES/shiftDescriptor.json'

# How the names of the cycle subdirectories are formatted
CYCLE_SUBDIRECTORY_NAME_FORMAT: '{experiment_name}_{cycle_number:0>2}'
# How to extract the experiment name and cycle number from a filename
EXPERIMENT_NAME_FROM_FILENAME: '^([^_]+)'
CYCLE_NR_FROM_FILENAME: '_(\d+)_'

# Where the image folder is located
IMAGE_FOLDER_LOCATION: '{cycle_subdirectory}/TIFF'

# Where the segmentation folder is located
SEGMENTATION_FOLDER_LOCATION: '{cycle_subdirectory}/SEGMENTATION'

# Where the illumination statistics files are located
STATS_FOLDER_LOCATION: '{cycle_subdirectory}/BATCH'

# How do determine the name of the illumination statistics filename
STATS_FILE_FORMAT: 'Measurements_batch_illcor_channel{channel_number:0>3}_zstack000.mat'
CHANNEL_NR_FROM_FILENAME: 'C(\d+)\.png$'

# Where the measurement folder is located
MEASUREMENT_FOLDER_LOCATION: '{cycle_subdirectory}/data'

# How the global cell_id should look like (used to save outlines in hd5f)
CELL_ID_FORMAT: '{site_row_nr}-{site_col_nr}-{cell_id}'
