---
version: '2'

services:

  web:
    command:
      - 'dumb-init'
      - '/usr/bin/gulp'
      - '--gulpfile'
      - '/home/tissuemaps/tmui/src/gulpfile.js'

  app:
    command:
      - 'dumb-init'
      - '/home/tissuemaps/.tmaps/tm_server.sh'
      - '-vv'
