---
project:
  description: ''
  lib: ''
input:
  channels: []
pipeline:
- active: true
  handle: handle/smooth_image_dapi.handle.yml
  source: smooth_image.py
- active: true
  handle: handle/threshold_image.handle.yml
  source: threshold_image.py
- active: true
  handle: handle/fill_mask.handle
  source: fill_mask.py
- active: true
  handle: handle/separate_objects.handle.yml
  source: separate_objects.m
- active: true
  handle: handle/filter_objects.handle.yml
  source: filter_objects.py
- active: true
  handle: handle/save_nuclei.handle
  source: save_objects.py
- active: true
  handle: handle/smooth_image_celltrace.handle.yml
  source: smooth_image.py
- active: true
  handle: handle/identify_cells.handle.yml
  source: identify_secondary_objects_iw.m
- active: true
  handle: handle/save_cells.handle.yml
  source: save_objects.py
- active: true
  handle: handle/relate_objects.handle.yml
  source: relate_objects.py

