---
# handlers file for tmaps-db-server
- name: restart postgresql
  become: yes
  service:
    name=postgresql
    state=restarted
    pattern='/usr/lib/postgresql/{{ postgresql_version }}/bin/postgres -D '
