---

- name: Ganglia collector playbook
  hosts: ganglia_master:ganglia_collector
  any_errors_fatal: yes
  roles:
    - ganglia-gmetad
    - ganglia-gmond
  tags:
    - ganglia
    - ganglia-gmetad
    - ganglia-gmond
    - gmetad


- name: Ganglia monitor playbook
  hosts: ganglia_monitor
  any_errors_fatal: yes
  roles:
    - ganglia-gmond
  tags:
    - ganglia
    - ganglia-gmond
    - gmond


- name: Ganglia frontend playbook
  hosts: ganglia_master:ganglia_web
  any_errors_fatal: yes
  roles:
    - ganglia-web
  tags:
    - ganglia
    - ganglia-webfrontend
    - ganglia-web
