- name: Clone source code repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ dest_dir }}"
    version: "{{ version }}"
    force: yes

- name: Install source package dependencies
  shell: |
    env PYTHONUSERBASE="{{ tm_home }}/.local" pip install -r "{{ item }}/requirements.txt" --user --no-cache-dir
  args:
    chdir: "{{ item }}"
    executable: /bin/bash
  with_items: "{{ pkg_dirs }}"

- name: Install source package
  shell: |
    env PYTHONUSERBASE="{{ tm_home }}/.local" pip install -e "{{ item }}" --user --no-cache-dir
  args:
    chdir: "{{ item }}"
    executable: /bin/bash
  with_items: "{{ pkg_dirs }}"
