---
- name: Update all packages to the latest version (Ubuntu)
  become: yes
  apt: upgrade=safe update_cache=yes cache_valid_time=3600

- name: Install apt packages for OpenCV
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - cmake
    - libboost-python-dev
    - libopencv-dev
  tags:
    - opencv
    - python

- name: Check if OpenCV was built
  stat: path="{{ deploy_home_folder }}/opencv/lib/python2.7/dist-packages/cv2.so"
  register: opencv_was_built
  tags:
    - opencv
    - python

- name: Install numpy Python package
  pip: name={{ item }} extra_args='--user'
  with_items:
    - numpy
  when: opencv_was_built.stat.exists == False
  tags:
    - opencv
    - python

- name: Get the latest OpenCV code
  git: repo="https://github.com/Itseez/opencv.git"
       dest="{{ deploy_home_folder }}/opencv"
       accept_hostkey=yes
       update=yes
       clone=yes
       force=yes
       version={{ opencv_version }}
  when: opencv_was_built.stat.exists == False
  vars:
    opencv_version: 3.1.0
  tags:
    - opencv
    - python

- file: path="{{ deploy_home_folder }}/opencv/build" state=directory
  when: opencv_was_built.stat.exists == False
  tags:
    - opencv
    - python

- name: Configure and compile OpenCV
  shell: |
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local ../
    make -j4
  args:
    chdir: "{{ deploy_home_folder }}/opencv/build"
  when: opencv_was_built.stat.exists == False
  tags:
    - opencv
    - python

- name: Install OpenCV (system wide)
  become: yes
  shell: "make install && ldconfig"
  args:
    chdir: "{{ deploy_home_folder }}/opencv/build"
  when: opencv_was_built.stat.exists == False
  tags:
    - opencv
    - python

- name: "Sanity check if cv2_so was installed into opencv folders"
  stat: path="/usr/local/lib/python2.7/dist-packages/cv2.so"
  register: cv2_so_installed
- fail: msg="Whoops! missing cv2.so module. Remove opencv folder and rerun playbooks."
  when: cv2_so_installed.stat.exists == False
  tags:
    - opencv
    - python
