---
# Warning, this is not safe.
- file: path={{ deploy_home_folder }}/.ssh state=directory

- name: Enable confirmation-free outgoing ssh connections
  template: src=ssh_config.j2 dest={{ deploy_home_folder }}/.ssh/config
