---
- name: Install apt packages required by TissueMAPS Python packages
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    # h5py:
    - libhdf5-dev
    - hdf5-tools
    # lxml:
    - libxml2-dev
    - libxslt1-dev
    # javabridge
    - openjdk-7-jdk
    # matplotlib:
    - pyqt4-dev-tools
    - libfreetype6-dev
    # shapely:
    - libgeos-dev
  tags:
    - tissuemaps

- name: Install numpy and cython Python packages
  become: yes
  command: /usr/local/bin/pip install cython --upgrade
  # Using the pip module doesn't work???
  # pip: name=cython
  tags:
    - tissuemaps

- name: Clone JtLibrary repository
  git:
    repo={{ tm_github_url }}/jtlibrary
    dest={{ ansible_env.HOME }}/jtlibrary
    version={{ jtlibrary_branch }}
    force=yes
  tags:
    - tissuemaps

- name: Install jtlibrary package
  shell: pip install -e {{ ansible_env.HOME }}/jtlibrary --user --process-dependency-links
  args:
    chdir={{ ansible_env.HOME }}/jtlibrary/
    executable=/bin/bash
  tags:
    - tissuemaps

# - name: Install jtlibrary package
#   pip:
#     name: "git+{{ tm_github_url }}/jtlibrary@{{ jtlibrary_branch }}#egg=jtlibrary"
#     extra_args: "--user --process-dependency-links"
#   tags:
#     - tissuemaps

- name: Clone JtModules repository
  git:
    repo={{ tm_github_url }}/jtmodules
    dest={{ ansible_env.HOME }}/jtmodules
    version={{ jtmodules_branch }}
    force=yes
  tags:
    - tissuemaps

- name: Install jtmodules package
  shell: pip install -e {{ ansible_env.HOME }}/jtmodules --user --process-dependency-links
  args:
    chdir={{ ansible_env.HOME }}/jtmodules/
    executable=/bin/bash
  tags:
    - tissuemaps

# - name: Install jtmodules package
#   pip:
#     name: "git+{{ tm_github_url }}/jtmodules@{{ jtmodules_branch }}#egg=jtmodules"
#     extra_args: "--user --process-dependency-links"
#   tags:
#     - tissuemaps

- name: Clone TmLibrary repository
  git:
    repo={{ tm_github_url }}/tmlibrary
    dest={{ ansible_env.HOME }}/tmlibrary
    version={{ tmlibrary_branch }}
    force=yes
  tags:
    - tissuemaps

- name: Install tmlibrary package
  shell: pip install -e {{ ansible_env.HOME }}/tmlibrary --user --process-dependency-links
  args:
    chdir={{ ansible_env.HOME }}/tmlibrary/
    executable=/bin/bash
  tags:
    - tissuemaps

# - name: Install tmlibrary package
#   pip:
#     name: "git+{{ tm_github_url }}/tmlibrary@{{ tmlibrary_branch }}#egg=tmlibrary"
#     extra_args: "--user --process-dependency-links"
#   tags:
#     - tissuemaps

- name: Clone TmToolbox repository
  git:
    repo={{ tm_github_url }}/tmtoolbox
    dest={{ ansible_env.HOME }}/tmtoolbox
    version={{ tmtoolbox_branch }}
  tags:
    - tissuemaps

- name: Install tmtoolbox package
  shell: pip install -e {{ ansible_env.HOME }}/tmtoolbox --user --process-dependency-links
  args:
    chdir={{ ansible_env.HOME }}/tmtoolbox/
    executable=/bin/bash
  tags:
    - tissuemaps

# - name: Install tmtoolbox package
#   pip:
#     name: "git+{{ tm_github_url }}/tmtoolbox@{{ tmtoolbox_branch }}#egg=tmtoolbox"
#     extra_args: "--user --process-dependency-links"
#   tags:
#     - tissuemaps

- name: Create directory for TissueMAPS related files
  file: path={{ ansible_env.HOME }}/.tmaps state=directory
  tags:
    - tissuemaps
    - config

- name: Create TissuMAPS library part of the configuration
  shell: "{{ tmaps_install_location }}/tm_create_config"
  tags:
    - tissuemaps
    - config

