---
- name: Install apt packages required by TissueMAPS Python packages
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    # h5py:
    - libhdf5-dev
    - hdf5-tools
    # lxml:
    - libxml2-dev
    - libxslt1-dev
    # javabridge
    - openjdk-7-jdk
    # matplotlib:
    - pyqt4-dev-tools
    - libfreetype6-dev
    # shapely:
    - libgeos-dev
  tags:
    - python
    - tissuemaps

- name: Install numpy and cython Python packages
  become: yes
  pip: name={{ item }} extra_args='--user'
  with_items:
    - numpy
    - cython
  tags:
    - python

- name: Install jtlibrary package
  pip:
    name: "git+{{ tm_github_url }}/jtlibrary@{{ jtlibrary_branch }}#egg=jtlibrary"
    extra_args: "--user --process-dependency-links"
  tags:
    - python
    - tissuemaps
    - git

- name: Install jtmodules package
  pip:
    name: "git+{{ tm_github_url }}/jtmodules@{{ jtmodules_branch }}#egg=jtmodules"
    extra_args: "--user --process-dependency-links"
  tags:
    - python
    - tissuemaps
    - git

- name: Install tmlibrary package
  pip:
    name: "git+{{ tm_github_url }}/tmlibrary@{{ tmlibrary_branch }}#egg=tmlibrary"
    extra_args: "--user --process-dependency-links"
  tags:
    - python
    - tissuemaps
    - git

- name: Install tmtoolbox package
  pip:
    name: "git+{{ tm_github_url }}/tmtoolbox@{{ tmtoolbox_branch }}#egg=tmtoolbox"
    extra_args: "--user --process-dependency-links"
  tags:
    - python
    - tissuemaps
    - git

- name: Create directory for TissueMAPS related files
  file: path={{ deploy_home_folder }}/.tmaps state=directory
  tags:
    - tissuemaps
    - config

- name: Create TissuMAPS library part of the configuration
  shell: "{{ tmaps_install_location }}/tm_create_config"
  tags:
    - tissuemaps
    - python
    - config

