---
project:
  description: ''
  lib: ''
input:
  channels: []
pipeline:
- active: true
  handle: handle/load_nuclei.handle.yml
  source: load_objects.py
- active: true
  handle: handle/measure_morphology_nuclei.handle.yml
  source: measure_morphology.py
- active: true
  handle: handle/measure_intensity_nuclei.handle.yml
  source: measure_intensity.py
- active: true
  handle: handle/measure_texture_nuclei.handle.yml
  source: measure_texture.py
- active: true
  handle: handle/load_cells.handle.yml
  source: load_objects.py
- active: true
  handle: handle/measure_morphology_cells.handle.yml
  source: measure_morphology.py
- active: true
  handle: handle/measure_intensity_cells.handle.yml
  source: measure_intensity.py
- active: true
  handle: handle/measure_texture_cells.handle.yml
  source: measure_texture.py
