# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2018  University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
# NOTE: We install all TissueMAPS python packages into the home folder because
# we export this folder on the cluster. This is convenient, because packages
# can then be updated on the frontend only and these changes become immediately
# effective on all compute nodes.

# This shouldn't be necessary, but some packages don't build correctly when
# cython and numpy are not already installed.
- name: Install cython and numpy packages
  shell: PYTHONUSERBASE={{ tm_home }}/.local pip install {{ item }} --user --no-cache-dir
  args:
    chdir: "{{ tm_home }}"
    executable: /bin/bash
  with_items:
    - cython==0.25.2
    - numpy==1.12.1
  tags:
    - tissuemaps

- name: Install JtLibrary repository
  tags:
    - tissuemaps
    - jtlibrary
  include: _clone.yml
  vars:
    repo_url: "{{ tm_github_url }}/jtlibrary"
    version: "{{ tm_version }}"
    dest_dir: "{{ tm_home }}/jtlibrary"
    pkg_dirs:
      - "{{ tm_home }}/jtlibrary/python/jtlibrary"
      - "{{ tm_home }}/jtlibrary/python/jtmodules"

- name: Compile MEX files in JtLibrary
  tags:
    - tissuemaps
    - jtlibrary
    - matlab
  shell: |
    if (command -v matlab > /dev/null); then
      dirname=$(dirname "{{ item }}")
      filename=$(basename "{{ item }}")
      mexname=${filename%%.*}
      cd "{{ tm_home }}/jtlibrary/matlab/$dirname"
      matlab -r "mex ${mexname}"
    else
      echo "Cannot find 'matlab' executable on PATH - skipping MEX compilation"
    fi
  with_items:
    - 'jtlibrary/+cpsub/IdentifySecPropagateSubfunction.cpp'

- name: Install TmLibrary repository
  tags:
    - tissuemaps
    - tmlibrary
  include: _clone.yml
  vars:
    repo_url: "{{ tm_github_url }}/tmlibrary"
    version: "{{ tm_version }}"
    dest_dir: "{{ tm_home }}/tmlibrary"
    pkg_dirs:
      - "{{ tm_home }}/tmlibrary"

- name: Create directory for TissueMAPS related files
  file:
    path: "{{ tm_home }}/.tmaps"
    state: directory
  tags:
    - tissuemaps

- name: Set permissions for home folder
  file:
    path: "{{ tm_home }}"
    state: directory
    recurse: yes
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
    mode: 0700
  tags:
    - tissuemaps
