# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
# (Re)start services and enable them such that they will be automatically
# started upon system startup.
# We don't do this within the respective roles for compatibility with
# Ansible-container.
- name: Refresh tmpfiles.d
  hosts: all
  tasks:
    - name: Create directories defined in tmpfiles.d
      command: systemd-tmpfiles --create

- name: Restart database master server
  hosts:
    - tissuemaps_db_master
  tasks:
    - name: Restart and enable postgresql service
      systemd:
        name: postgresql@master
        daemon_reload: yes
        state: restarted
        enabled: yes

- name: Restart database worker servers
  hosts:
    - tissuemaps_db_worker
  tasks:
    - name: Restart and enable postgresql service
      systemd:
        name: postgresql@worker
        daemon_reload: yes
        state: restarted
        enabled: yes

- name: Restart web and application servers
  hosts:
    - tissuemaps_server
  tasks:
    - name: Restart and enable nginx service
      systemd:
        name: nginx
        state: restarted
        daemon_reload: yes
        enabled: yes
    - name: Restart and enable uwsgi service
      systemd:
        name: uwsgi
        state: restarted
        daemon_reload: yes
        enabled: yes

