# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2019 University of Zurich.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
# Github user names of administrators;
# these people will have their SSH key deployed
# on to all nodes
tm_admins: []

# user name of the system user running the TM services
tm_user: tissuemaps

# what TCP port should TM be accessible on
tm_web_port: 80

# contact data for the database server
#
# FIXME: I'm not sure it makes much sense to go through hoops just to
# have connections go to `localhost` or a UNIX-domain socket; this
# only applies to the master, the real data connections are to the
# workers, which are always contacted via TCP...
#
tm_db_host: "{{ groups.tissuemaps_db_master[0] if groups.tissuemaps_db_master else 'localhost' }}"
