- name: Update all packages to the latest version
  become: yes
  tags:
    - update
  apt: upgrade=safe update_cache=yes cache_valid_time=3600

- name: Add postgresql repo (url)
  lineinfile: "dest=/etc/apt/sources.list.d/pgdg.list state=present create=yes regexp='^deb http\\:\\/\\/apt.postgresql' line='deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main'"
  become: yes
  register: pgs_aptrepo
  tags:
    - postgresql

- name: Add postgresql repo (key)
  become: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present validate_certs=no
  register: pgs_aptkey
  tags:
    - postgresql

- name: Update packages to add postgresql
  become: yes
  tags:
    - update
    - postgresql
  shell: "aptitude update"
  when: pgs_aptkey.changed or pgs_aptrepo.changed

- name: Install apt packages
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - postgresql-{{ postgresql_version }}
    - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}
    - postgresql-{{ postgresql_version }}-postgis-scripts
    - postgresql-contrib-{{ postgresql_version }}
    - postgresql-server-dev-all
    - postgresql-client
    - python-psycopg2
  notify:
    - restart postgresql
  tags:
    - postgresql

- name: Add postgres executable to PATH
  lineinfile: dest="{{ deploy_home_folder }}/.bash_profile" line='export PATH=/usr/lib/postgresql/{{ postgresql_version }}/bin:$PATH'
  tags:
    - postgresql
