---
# Github user names of administrators;
# these people will have their SSH key deployed
# on to all nodes
tm_admins: []

# Create user accounts on the TissueMAPS service.
# This should be a YAML list, each item of which
# must have three fields: name, password, and email.
# Example:
#
#   tm_create_users:
#     - name: foo
#       password: bar
#       email: foo@example.org
#     - name: baz
#       password: xyz
#       email: baz@example.org
#
# Note that passwords are cleartext here!
#
# The default is not to create any TM-level user.
tm_create_users: []

tm_repo_url: https://github.com/TissueMAPS/TissueMAPS.git
tm_version: master

# root directory for all TissueMAPS-related files
tm_root: '/srv/tissuemaps'

# where the TM server will store uploaded files, workflow results, etc
tm_storage_home: '{{ tm_root }}/var/filesystem'

# UNIX user data of the system user running TM services
tm_user: tissuemaps
tm_group: tissuemaps
tm_user_home: '/home/{{ tm_user }}'

# what TCP port should TM be accessible on
tm_web_port: 80

# contact data for the database server
#
# FIXME: I'm not sure it makes much sense to go through hoops just to
# have connections go to `localhost` or a UNIX-domain socket; this
# only applies to the master, the real data connections are to the
# workers, which are always contacted via TCP...
#
tm_db_host: "{{ groups.tissuemaps_db_master[0] if groups.tissuemaps_db_master else 'localhost' }}"
