# TmSetup - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: Update all packages to the latest version
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - nginx
    - web-server

- name: Install nginx
  apt:
    name: nginx
    state: installed
  tags:
    - web-server
    - nginx

- name: Create nginx site
  template:
    src: nginx_site.j2
    dest: /etc/nginx/sites-available/tissuemaps
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
  tags:
    - nginx
    - web-server

- name: Place site specific nginx conf.d
  template:
    src: nginx_conf.j2
    dest: /etc/nginx/conf.d/tissuemaps.conf
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
  tags:
    - nginx
    - web-server

- name: Change nginx user for worker processes
  lineinfile:
    dest: /etc/nginx/nginx.conf
    state: present
    regexp: 'user\s+.*;'
    line: 'user {{ tm_user }};'
  tags:
    - nginx
    - web-server

# We may want to run nginx as a non-root user, e.g. within a container.
- name: Give user permission to nginx directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
  with_items:
    - /var/lib/nginx
    - /var/log/nginx
    - /usr/share/nginx
    - /etc/nginx
  tags:
    - nginx
    - web-server

- name: Enable nginx site
  shell: |
    if [ ! -s /etc/nginx/sites-enabled/tissuemaps ]; then
      ln -s /etc/nginx/sites-available/tissuemaps /etc/nginx/sites-enabled/tissuemaps
    fi
    if [ -s /etc/nginx/sites-enabled/default ]; then
      rm /etc/nginx/sites-enabled/default
    fi
  tags:
    - nginx
    - web-server
