TmSetup - Automated setup and deployment of TissueMAPS in the cloud.
Copyright (C) 2016  Markus D. Herrmann, University of Zurich

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: Update all packages to the latest version (Ubunutu)
  become: yes
  apt: upgrade=safe update_cache=yes cache_valid_time=3600
  tags:
    - spark

- name: Install Spark dependencies (Ubuntu)
  become: yes
  apt: name={{ item }} state=installed
  with_items:
    - openjdk-7-jdk
    - maven
  tags:
    - spark

# - name: Remove Spark code
#   file: path={{ ansible_env.HOME }}/spark state=absent
#   tags:
#     - spark

- name: Register "spark" directory
  stat: path={{ ansible_env.HOME }}/spark
  register: spark_source_code
  tags:
    - spark

- name: Download Spark source code
  get_url:
    url="http://d3kbcqa49mib13.cloudfront.net/spark-{{ spark_version }}.tgz"
    dest={{ ansible_env.HOME }}
  when: spark_source_code.stat.exists == false
  tags:
    - spark

- name: Unarchive downloaded Spark source code
  unarchive:
    src={{ ansible_env.HOME }}/spark-{{ spark_version }}.tgz
    dest={{ ansible_env.HOME }}
    copy=no
  when: spark_source_code.stat.exists == false
  tags:
    - spark

- name: Move unarchived Spark code into "spark" directory
  command: mv {{ ansible_env.HOME }}/spark-{{ spark_version }} {{ ansible_env.HOME }}/spark
  when: spark_source_code.stat.exists == false
  tags:
    - spark

- name: Remove Spark code archive
  file: path={{ ansible_env.HOME }}/spark-{{ spark_version }}.tgz state=absent
  tags:
    - spark

- name: Install Spark from source
  shell: "{{ ansible_env.HOME }}/spark/build/mvn -Pyarn -Phadoop-{{ hadoop_distribution }} -Dhadoop.version={{ hadoop_version }} -Phive -Phive-thriftserver -DskipTests clean package"
  args:
    chdir: "{{ ansible_env.HOME }}/spark/"
  environment:
    JAVA_HOME: "/usr/lib/jvm/java-1.7.0-openjdk-amd64"
    MAVEN_OPTS: "-Xmx2g -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m"
  tags:
    - spark
