# TmSetup - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: Install apt packages required by TissueMAPS Python packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    # h5py:
    - libhdf5-dev
    - hdf5-tools
    # lxml:
    - libxml2-dev
    - libxslt1-dev
    # javabridge:
    - openjdk-8-jdk  # openjdk-7-jdk
    # matplotlib:
    - pyqt4-dev-tools
    - libfreetype6-dev
    - python-tk
    # shapely:
    - libgeos-dev
  tags:
    - tissuemaps


# NOTE: We install all TissueMAPS python packages into the home folder because
# we export this folder on the cluster. This is convenient, because packages
# can then be updated on the frontend only and these changes become immediatly
# effective on all compute nodes.

- name: Install cython package
  # command: /usr/local/bin/pip install cython --upgrade
  # TODO: Using the pip module doesn't work???
  pip:
    name: cython
    editable: false
  tags:
    - tissuemaps

# This shouldn't be necessary, but some packages don't build correctly when
# numpy is not already installed.
- name: Install numpy package
  pip:
    name: numpy
    editable: false
  tags:
    - tissuemaps

- name: Clone JtLibrary repository
  become_user: "{{ tm_user }}"
  git:
    repo: "{{ tm_github_url }}/jtlibrary"
    dest: "{{ tm_home }}/jtlibrary"
    version: "{{ tm_version }}"
    force: yes
  tags:
    - tissuemaps

- name: Install jtlibrary package
  become_user: "{{ tm_user }}"
  shell: pip install -e {{ tm_home }}/jtlibrary --user
  args:
    chdir: "{{ tm_home }}/jtlibrary/"
    executable: /bin/bash
  tags:
    - tissuemaps

- name: Clone JtModules repository
  become_user: "{{ tm_user }}"
  git:
    repo: "{{ tm_github_url }}/jtmodules"
    dest: "{{ tm_home }}/jtmodules"
    version: "{{ tm_version }}"
    force: yes
  tags:
    - tissuemaps

- name: Install jtmodules package
  become_user: "{{ tm_user }}"
  shell: pip install -e {{ tm_home }}/jtmodules --user
  args:
    chdir: "{{ tm_home }}/jtmodules/"
    executable: /bin/bash
  tags:
    - tissuemaps

# NOTE: When including the GC3Pie dependency via --process-dependency-links
# upon installation of tmlibrary, I get HTTP erros when installing on multiple
# hosts simulatneously???
- name: Clone GC3Pie repository
  become_user: "{{ tm_user }}"
  git:
    repo: "{{ tm_github_url }}/gc3pie"
    dest: "{{ tm_home }}/gc3pie"
    version: master
    force: yes
  tags:
    - tissuemaps

- name: Install gc3pie package
  become_user: "{{ tm_user }}"
  shell: pip install -e {{ tm_home }}/gc3pie --user
  args:
    chdir: "{{ tm_home }}/gc3pie"
    executable: /bin/bash
  tags:
    - tissuemaps

- name: Clone TmLibrary repository
  become_user: "{{ tm_user }}"
  git:
    repo: "{{ tm_github_url }}/tmlibrary"
    dest: "{{ tm_home }}/tmlibrary"
    version: "{{ tm_version }}"
    force: yes
  tags:
    - tissuemaps

- name: Install tmlibrary package
  become_user: "{{ tm_user }}"
  shell: pip install -e {{ tm_home }}/tmlibrary --user
  args:
    chdir: "{{ tm_home }}/tmlibrary/"
    executable: /bin/bash
  tags:
    - tissuemaps

- name: Create directory for TissueMAPS related files
  become_user: "{{ tm_user }}"
  file:
    path: "{{ tm_home }}/.tmaps"
    state: directory
  tags:
    - tissuemaps
