# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
# We need to remove an existing database cluster, otherwise initdb will fail.
- name: Stop running default database server
  become_user: "{{ db_superuser }}"
  command: "{{ db_executable_directory }}/pg_ctl stop -D {{ db_default_cluster_directory }}"
  ignore_errors: yes
  tags:
    - database

- name: Remove existing default data directory
  file:
    path: "{{ db_default_cluster_directory }}"
    state: absent
  tags:
    - database

- name: Stop running database server
  become_user: "{{ db_superuser }}"
  command: '{{ db_executable_directory }}/pg_ctl stop -D {{ db_data_directory }}/{{ postgresql_version }}/{{ db_node }} -o "-p {{ db_port }}" -m smart'
  ignore_errors: yes
  tags:
    - database

- name: Remove existing data directory
  file:
    path: "{{ db_data_directory }}/{{ postgresql_version }}/{{ db_node }}"
    state: absent
  tags:
    - database

- name: Initialize database cluster
  become_user: "{{ db_superuser }}"
  command: "{{ db_executable_directory }}/pg_ctl init -D {{ db_data_directory }}/{{ postgresql_version }}/{{ db_node }} -l {{ db_log_directory }}/postgresql-{{ postgresql_version }}-{{ db_node }}.log"
  tags:
    - database

- name: Increase kernel limits for semaphores
  shell: sysctl -w kernel.sem="250 60000 32 250"
  tags:
    - database

- name: Increaese limit for number of open files
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ db_superuser }} soft nofile {{ pg_max_files_per_process }}"
  tags:
    - database

- name: Place PostgreSQL systemd config file
  template:
    src: postgresql.service.j2
    dest: /etc/systemd/system/postgresql@{{ db_node }}.service
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
  when:
    - ansible_env.ANSIBLE_CONTAINER is undefined
  tags:
    - database

- name: Create directory for PostgreSQL lock file
  file:
    path: /var/run/postgresql
    state: directory
    recurse: yes
    owner: "{{ db_superuser }}"
    group: "{{ db_superuser }}"
    mode: 0700
  tags:
    - database
