# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: Get Citus repository
  command: wget https://install.citusdata.com/community/rpm.sh -O {{ tm_home }}/citus_rpm.sh
  args:
    executable=/bin/bash
    chdir={{ tm_home }}
  # get_url:
  #   url: https://install.citusdata.com/community/rpm.sh
  #   dest: "{{ tm_home}}/citus_rpm.sh"
  #   validate_certs: no
  #   unsafe_writes: yes
  #   timeout: 60
  #   mode: 0770
  when: ansible_os_family == 'RedHat'
  tags:
    - database

- name: Make Citus install script executable
  file:
    path={{ tm_home }}/citus_rpm.sh
    mode=0770
  when: ansible_os_family == 'RedHat'
  tags:
    - database

- name: Add Citus repository
  command: "{{ tm_home }}/citus_rpm.sh"
  args:
    # FIXME
    creates: /etc/apt/sources.list.d/citusdata_community.list
  when: ansible_os_family == 'RedHat'
  tags:
    - database

- name: Install Citus PostgreSQL
  yum:
    state: installed
    name: "{{ item }}"
  when: ansible_os_family == 'RedHat'
  with_items:
    - citus{{ citus_version | regex_replace('^(\\d).(\\d)$', '\\1\\2') }}_{{ postgresql_version | regex_replace('^(\\d).(\\d)$', '\\1\\2') }}
    - postgis{{ postgis_version | regex_replace('^(\\d).(\\d)$', '\\1') }}_{{ postgresql_version | regex_replace('^(\\d).(\\d)$', '\\1\\2') }}
    - python-psycopg2
  tags:
    - database

- name: Install setfacl support
  yum:
    name: acl
  when: ansible_os_family == 'RedHat'
  tags:
    - database
