---
volume_fstype: ext4
instance_name: "{{ inventory_hostname }}"
volume_name: "{{ instance_name }}-storage"
volume_device:
  os: /dev/vdb
  ec2: /dev/sdf
  gce: /dev/disk/by-id/google-{{ volume_name }}
