# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: Place NGINX configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
    mode: 0700
  tags:
    - web-server
    - nginx

- name: Place site specific NGINX conf.d
  template:
    src: tissuemaps.conf.j2
    dest: /etc/nginx/conf.d/tissuemaps.conf
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
    mode: 0700
  tags:
    - web-server
    - nginx

- name: Create directory for NGINX log files
  file:
    path: "{{ tm_log_directory }}"
    state: directory
    recurse: yes
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
    mode: 0700
  tags:
    - web-server
    - nginx

- name: Create NGINX log files with correct permissions
  file:
    path: "{{ tm_log_directory }}/{{ item }}"
    state: touch
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
    mode: 0700
  with_items:
    - nginx-access.log
    - nginx-error.log
  tags:
    - web-server
    - nginx

- name: Create directory for NGINX pid file
  file:
    path: /var/run/nginx
    state: directory
    recurse: yes
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
    mode: 0700
  tags:
    - web-server
    - nginx

- name: Place NGINX systemd service file
  template:
    src: nginx.service.j2
    dest: /lib/systemd/system/nginx.service
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
  when:
    - ansible_env.ANSIBLE_CONTAINER is undefined
  tags:
    - web-server
    - nginx

# We may want to run nginx as a non-root user, e.g. within a container.
- name: Give user permission to NGINX directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ tm_user }}"
    group: "{{ tm_user }}"
    mode: 0700
  with_items:
    - /var/lib/nginx
    - /var/log/nginx
    - /var/run/nginx
    - /usr/share/nginx
    - /etc/nginx
  tags:
    - web-server
    - nginx
