---
- name: Check if the volume has already been formatted and mounted
  command: mountpoint -q {{ volume_mount_point }}
  register: mount_point
  tags:
    - volume

- debug:
    msg: Mountpoint {{ volume_mount_point }} is already mounted!
  when: mount_point.rc == 0

- name: Install required packages
  become: yes
  apt:
    name={{ item }}
    state=present
  with_items:
    - util-linux
    - parted
    - lvm2
  tags:
    - volume

- include: format.yml
  when: mount_point.rc == 1

- include: mount.yml
  when: mount_point.rc == 1
