---
- name: Update all packages to the latest version (Ubunutu)
  become: yes
  apt: upgrade=safe update_cache=yes cache_valid_time=3600
  tags:
    - spark

- name: Install Spark dependencies (Ubuntu)
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - openjdk-7-jdk
    - maven
  tags:
    - spark

- name: Register "spark" directory
  stat: path={{ deploy_home_folder }}/spark
  register: spark_folder
  tags:
    - spark

- name: Download Spark source code
  get_url:
    url: "http://d3kbcqa49mib13.cloudfront.net/spark-{{ spark_version }}.tgz"
    dest: "{{ deploy_home_folder }}"
  when: spark_folder.stat.exists == false
  tags:
    - spark

- name: Unarchive downloaded Spark source code
  unarchive:
    src: "{{ deploy_home_folder }}/spark-{{ spark_version }}.tgz"
    dest: "{{ deploy_home_folder }}"
    copy: no
  when: spark_folder.stat.exists == false
  tags:
    - spark

- name: Move unarchived Spark code into "spark" directory
  command: mv {{ deploy_home_folder }}/spark-{{ spark_version }} {{ deploy_home_folder }}/spark
  when: spark_folder.stat.exists == false
  tags:
    - spark

- name: Install Spark from source
  shell: "{{ deploy_home_folder }}/spark/build/mvn -Pyarn -Phadoop-{{ hadoop_distribution }} -Dhadoop.version={{ hadoop_version }} -Phive -Phive-thriftserver -DskipTests clean package"
  args:
    chdir: "{{ deploy_home_folder }}/spark"
  environment:
    JAVA_HOME: "/usr/lib/jvm/java-1.7.0-openjdk-amd64"
    MAVEN_OPTS: "-Xmx2g -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m"
  tags:
    - spark
