# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2019 University of Zurich.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
# (Re)start services and enable them such that they will be automatically
# started upon system startup.
# We don't do this within the respective roles for compatibility with
# Ansible-container.
- name: Refresh tmpfiles.d
  hosts: all
  gather_facts: yes
  any_errors_fatal: yes
  tasks:
    - name: Create directories defined in tmpfiles.d
      command: systemd-tmpfiles --create
    - name: Restart ssh daemon service
      systemd:
        name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
        state: restarted

- name: Initialize database master server
  hosts:
    - tissuemaps_db_master
  gather_facts: yes
  any_errors_fatal: yes
  tasks:
    - name: Enable and start postgresql service
      systemd:
        name: postgresql@master
        daemon_reload: yes
        state: restarted
        enabled: yes

- name: Initialize database worker servers
  hosts:
    - tissuemaps_db_worker
  gather_facts: yes
  any_errors_fatal: yes
  tasks:
    - name: Enable and start postgresql service
      systemd:
        name: postgresql@worker
        daemon_reload: yes
        state: restarted
        enabled: yes

- name: Configure TissueMAPS application as database client
  hosts: tissuemaps_server
  gather_facts: yes
  vars:
    db_host_master: "{{ hostvars[groups['tissuemaps_db_master'][0]].ansible_host }}"
    db_hosts_workers: "{{ groups['tissuemaps_db_worker']|map('extract', hostvars, ['ansible_host'])|list }}"
    db_nodes: "{{ groups['tissuemaps_db_worker']|length|int }}"
  any_errors_fatal: yes
  roles:
    - database-client

- name: Start TissueMAPS web and application servers
  hosts: tissuemaps_server
  gather_facts: yes
  any_errors_fatal: yes
  tasks:
    - name: Start web server socket at boot
      systemd:
        name: uwsgi.socket
        state: started
        daemon_reload: yes
        enabled: yes
    - name: Enable uWSGI at boot
      systemd:
        name: uwsgi
        state: restarted
        daemon_reload: yes
        enabled: yes
