# TmSetup - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

- name: stop postgresql
  become: yes
  service: name=postgresql state=stopped
  tags:
    - postgresql

# Symlink /var/lib/postgresql -> /data/storage/postgresql/
- name: Create data directory (source for symlink) at /var/lib
  become: yes
  file:
    path=/var/lib/postgresql
    state=absent
  tags:
    - postgresql

- name: Create data directory (target for symlink) on mounted filesystem
  become: yes
  file:
    path={{ volume_mountpoint }}/storage/postgresql/data
    state=directory
    owner=postgres
    group=postgres
  tags:
    - postgresql

- name: Symlink data directory to mounted filesystem
  become: yes
  file: src={{ volume_mountpoint }}/storage/postgresql/data
    dest=/var/lib/postgresql
    state=link
    force=yes
    owner=postgres
    group=postgres
  tags:
    - postgresql

- name: Create version-specific data subdirectory
  become: yes
  file: path=/var/lib/postgresql/{{postgresql_version}}/main
    state=directory
    owner=postgres
    group=postgres
  tags:
    - postgresql

- name: Change ownership for data directory (give permissions to postgres user)
  become: yes
  file: path=/var/lib/postgresql/
    recurse=yes
    owner=postgres
    group=postgres
  tags:
    - postgresql

- name: Create log directory (source for symlink) at /var/log/postgresql
  become: yes
  file:
    path=/var/log/postgresql
    state=absent
  tags:
    - postgresql

- name: Create log directory (target for symlink) on mounted filesystem
  become: yes
  file:
    path={{ volume_mountpoint }}/storage/postgresql/logs
    state=directory
    owner=postgres
    group=postgres
  tags:
    - postgresql

- name: Symlink log directory to mounted filesystem
  become: yes
  file:
    src={{ volume_mountpoint }}/storage/postgresql/logs
    dest=/var/log/postgresql
    state=link
    force=yes
    owner=postgres
    group=postgres
  notify:
    - restart postgresql
  tags:
    - postgresql

- name: Install setfacl support
  become: yes
  apt:
    pkg=acl
    state=installed
  tags:
    - postgresql

- name: Initialize database cluster at created data directory
  become: yes
  become_user: postgres
  shell: "/usr/lib/postgresql/{{ postgresql_version }}/bin/initdb -D /var/lib/postgresql/{{ postgresql_version }}/main"
  args:
    creates: /var/lib/postgresql/{{ postgresql_version }}/main/base
  tags:
    - postgresql
