TmSetup - Automated setup and deployment of TissueMAPS in the cloud.
Copyright (C) 2016  Markus D. Herrmann, University of Zurich

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
- name: Update all packages to the latest version
  become: yes
  tags:
    - update
  apt: upgrade=safe update_cache=yes cache_valid_time=3600

- name: Add postgresql repo (key)
  become: yes
  apt_key: id=ACCC4CF8 url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present #validate_certs=no
  register: pgs_aptkey
  tags:
    - postgresql

- name: Add postgresql repo (url)
  become: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main'
  register: pgs_aptrepo
  tags:
    - postgresql

- name: Update packages to add postgresql
  become: yes
  apt: update_cache=yes
  # shell: "aptitude update"
  # when: pgs_aptkey.changed or pgs_aptrepo.changed
  tags:
    - update
    - postgresql

- name: Install PostgreSQL package
  become: yes
  apt:
    name: postgresql-{{ postgresql_version }}
    state: installed
  tags:
    - postgresql


- name: Install apt packages
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    # - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}
    - postgresql-{{ postgresql_version }}-postgis-scripts
    - postgresql-contrib-{{ postgresql_version }}
    - postgresql-server-dev-all
    - postgresql-client
    - python-psycopg2
  notify:
    - restart postgresql
  tags:
    - postgresql

- name: Ensure ".bash_profile" file exists
  file:
    path={{ ansible_env.HOME }}/.bash_profile
    state=touch
  tags:
    - postgresql

- name: Add postgres executable to PATH
  lineinfile:
    dest={{ ansible_env.HOME }}/.bash_profile
    line='export PATH=/usr/lib/postgresql/{{ postgresql_version }}/bin:$PATH'
  tags:
    - postgresql
