---
# Cooks images used to launch VMs of frontend and compute nodes.
- name: Install TmToolbox, TmLibrary, JtModules, and JtLibrary packages
  hosts: tissuemaps_compute
  roles:
    - tmaps-compute
  tags:
    - tissuemaps
    - compute
