---
# Ansible playbook for creating, terminating, starting and stopping virtual
# machine instsances in the cloud. The state of instances is controlled via the
# "instance_state" variable. Note that not all states are provided for all
# implemented providers.
- name: Provision virtual machine instances
  hosts: all
  vars:
    instance_state: present
  roles:
    - cloud-instance
