---
# Playbook for creating an instance on OpenStack (OS).
#
# Requires the following environment variables:
#  - OS_USERNAME
#  - OS_PASSWORD
#  - OS_TENANT_NAME
#  - OS_AUTH_URL
- name: Provisioning an instance within OpenStack (OS)
  hosts: tissuemaps_monitoring
  connection: local
  tasks:
    - name: Create instance
      os_server:
        name: "{{ cloud_instance_name }}"
        state: present
        key_name: tmaps_setup
        security_groups:
          - default
          - web
        image: "{{ cloud_image }}"
        flavor: "{{ cloud_flavor }}"
        timeout: 200
        auto_ip: yes
        wait: yes
        # volumes: 
        network: "{{ cloud_network }}"
      register: instance

    - name: Add instance to inventory
      add_host:
        name: "{{ cloud_instance_name }}"
        groups: tissuemaps_compute, tissuemaps_web, tissuemaps_database
        ansible_ssh_host: "{{ instance.openstack.public_v4 }}"
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: "{{ ansible_env.HOME }}/.ssh/tmaps_setup.pem"

    - name: Wait for instance
      wait_for:
        host: "{{ instance.openstack.public_v4 }}"
        port: 22
        delay: 10
        timeout: 60
        state: started
