---
- name: Install requirements for setting up TissueMAPS
  hosts: tissuemaps_monitor
  tasks:

    - include: roles/tmaps-common/tasks/python.yml

    - include: roles/tmaps-common/tasks/ssh.yml

    - include: roles/tmaps-common/tasks/utils.yml

    - name: Install virtualenv Python package
      become: yes
      pip: name=virtualenv

    - name: Install elasticluster requirements
      become: yes
      apt: name={{ item }}
      with_items:
        - git
        - gcc
        - g++
        - libc6-dev
        - libffi-dev
        - libssl-dev

    - name: Install ansible Python package into "tmaps_setup" virtualenv
      pip:
        name=ansible
        editable=false
        virtualenv={{ ansible_env.HOME }}/.virtualenvs/tmaps_setup
        virtualenv_python=python2.7

    - name: Install elasticluster Python package into "tmaps_setup" virtualenv
      pip:
        name="git+https://github.com/gc3-uzh-ch/elasticluster#egg=elasticluster"
        virtualenv={{ ansible_env.HOME }}/.virtualenvs/tmaps_setup
        virtualenv_python=python2.7

    - name: Clone TmSetup repository
      git:
        repo={{ tm_github_url }}/tmsetup
        dest={{ ansible_env.HOME }}/tmsetup

