---
- name: Install requirements for setting up TissueMAPS
  hosts: tissuemaps_monitor
  tasks:
    - include: roles/tmaps-common/tasks/python.yml
    - include: roles/tmaps-common/tasks/ssh.yml
    - include: roles/tmaps-common/tasks/utils.yml
    - name: Install virtualenv Python package
      become: yes
      pip: name=virtualenv
    - name: Create "tmaps_setup" virtualenv
      command: virtualenv {{ ansible_env.HOME }}/.virtualenvs/tmaps_setup -p python2.7 creates="{{ ansible_env.HOME }}/.virutalenvs/tmaps_setup" 
    - name: Install elasticluster requirements
      become: yes
      apt: name={{ item }}
      with_items:
        - git
        - gcc
        - g++
        - libc6-dev
        - libffi-dev
        - libssl-dev
    - name: Install Elasticluster Python package into "tmaps_setup" virtualenv
      pip:
        name="git+https://github.com/gc3-uzh-ch/elasticluster#egg=elasticluster"
        virtualenv={{ ansible_env.HOME }}/.vitualenvs/tmaps_setup
        virtualenv_python=python2.7
