---
# Playbook for creating a virtual machine instance on Elastic Compute Cloud 2 (EC2).
#
# Requires the following environment variables:
#  - AWS_ACCESS_KEY_ID
#  - AWS_SECRET_ACCESS_KEY
- name: Create instance
  ec2:
    state: present
    key_name: "{{ cloud_key_name }}"
    image: "{{ cloud_image }}"
    instance_type: "{{ cloud_flavor }}"
    count: 1
    instance_tags:
       Name: "{{ item }}"
    groups: "{{ cloud_security_groups }}"
    wait: true
    wait_timeout: 300
    volumes:
      # SSD device for root file system
      - device_name: /dev/sda1
        volume_size: "{{ cloud_disk_size }}"
        volume_type: gp2
        delete_on_termination: yes
    # ebs_optimized: no
    # assign_public_ip: yes
    # vpc_subnet_id: "{{ cloud_network }}"
    region: "{{ cloud_region }}"
  register: instance

- name: Create volume and attach it to the instance
  ec2_vol:
    state: present
    device_name: "{{ cloud_volume_device[cloud_provider] }}"
    instance: "{{ instance.instances[0].id }}"
    delete_on_termination: yes
    name: "{{ cloud_volume_name }}"
    region: "{{ cloud_region }}"
    volume_type: standard
    volume_size: "{{ cloud_volume_size }}"
  when: cloud_volume_size is defined

- debug:
    msg: Created instance {{ instance.instances[0].public_ip }}

- name: Wait for instance
  wait_for:
    host: "{{ instance.instances[0].public_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started

- name: Add instance to inventory
  add_host:
    name: "{{ item }}"
    ansible_ssh_host: "{{ instance.instances[0].public_ip }}"
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: "{{ ansible_env.HOME }}/.ssh/{{ cloud_key_name }}.pem"

- include: format.yml
  when: cloud_volue_size is defined

- include: mount.yml
  when: cloud_volue_size is defined
