---
# Playbook for creating a virtual machine instance on Gooble Compute Engine (GCE).
#
# Requires the following environment variables to be set:
#  - GCE_EMAIL
#  - GCE_PROJECT: name of your project
#  - GCE_CREDENTIALS_FILE_PATH: path to an credentials file in JSON format
#    (https://developers.google.com/identity/protocols/application-default-credentials)
- name: Create instance
  gce:
    state: present
    name: "{{ cloud_instance_name }}"
    image: "{{ cloud_image }}"
    machine_type: "{{ cloud_flavor }}"
    status: started
    # disks:
    subnetwork: "{{ cloud_network }}"
    zone: "{{ cloud_region }}"
  register: instance

- name: Add instance to inventory
  add_host:
     name: "{{ cloud_instance_name }}"
     groups: tissuemaps_compute, tissuemaps_web, tissuemaps_database
     ansible_ssh_host: "{{ instance.instances[0].public_ip }}"
     ansible_ssh_user: ubuntu
     ansible_ssh_private_key_file: "{{ ansible_env.HOME }}/.ssh/tmaps_setup.pem"

- name: Wait for instance to come up
  wait_for:
    host: "{{ instance.instances[0].public_ip }}"
    port: 22
    delay: 10
    timeout: 60
    state: started
