---
# Playbook for creating a virtual machine instance on Gooble Compute Engine (GCE).
#
# Requires the following environment variables to be set:
#  - GCE_EMAIL
#  - GCE_PROJECT
#  - GCE_CREDENTIALS_FILE_PATH: path to an credentials file in JSON format
#    (https://developers.google.com/identity/protocols/application-default-credentials)
- name: Create boot disk
  gce_pd:
    state: present
    zone: "{{ cloud_region }}"
    size_gb: "{{ cloud_disk_size }}"
    name: "{{ cloud_instance_name }}"
    mode: READ_WRITE

- name: Create volume
  gce_pd:
    state: present
    zone: "{{ cloud_region }}"
    size_gb: "{{ cloud_volume_size }}"
    name: "{{ cloud_volume_name }}"
    mode: READ_WRITE

- name: Create instance
  vars:
    ssh_key: "{{ lookup('file', '~/.ssh/{{ cloud_key_name }}.pub') }}"
  gce:
    state: present
    name: "{{ cloud_instance_name }}"
    image: "{{ cloud_image }}"
    machine_type: "{{ cloud_flavor }}"
    external_ip: ephemeral
    disks:
      - name: "{{ cloud_instance_name }}"
        mode: READ_WRITE
      - name: "{{ cloud_volume_name }}"
        mode: READ_WRITE
        device-name: "{{ cloud_volume_device }}"
    network: "{{ cloud_network }}"
    zone: "{{ cloud_region }}"
    metadata:
      ssh-keys: "ubuntu:{{ ssh_key }}"
    disk_auto_delete: yes
  register: instance

- debug:
    msg: Created instance {{ instance.instance_data[0].public_ip }}

- name: Add instance to inventory
  add_host:
     name: "{{ cloud_instance_name }}"
     groups: tissuemaps_compute, tissuemaps_web, tissuemaps_database
     ansible_ssh_host: "{{ instance.instance_data[0].public_ip }}"
     ansible_ssh_user: ubuntu
     ansible_ssh_private_key_file: "{{ ansible_env.HOME }}/.ssh/{{ cloud_key_name }}.pub"

- name: Wait for instance to come up
  wait_for:
    host: "{{ instance.instance_data[0].public_ip }}"
    port: 22
    delay: 10
    timeout: 60
    state: started
