---
# TODO: Create security group (firewall)
# os: os_security_group
# ec2: ec2_group
# gce: gce_net
- include: "{{provider}}.yml"

- debug:
    msg: Created instance {{ instance_public_ip }}
  when: instance_state == "present"

- name: Wait for instance
  local_action: wait_for
  args:
    host: "{{ instance_public_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  when: instance_state == "present"

# TODO: this does not trigger --refresh
- meta: refresh_inventory

- debug:
    msg: "{{ inventory_hostname }}: {{ ansible_host }}"

# - include: roles/cloud-instance/tasks/format.yml
#   delegate_to: "{{ instance_public_ip }}"
#   delegate_facts: yes
#   when: (volume_size is defined) and (instance_state == "present")

# - include: roles/cloud-instance/tasks/mount.yml
#   delegate_to: "{{ instance_public_ip }}"
#   delegate_facts: yes
#   when: (volume_size is defined) and (instance_state == "present")
