---
- name: Ensure that group exists for storage volume
  become: yes
  group: name={{ volume_group }}
  tags:
    - volume

- name: Ensure that user exist for storage volume
  become: yes
  user:
      name={{ volume_user }}
      group={{ volume_group }}
      shell=/bin/bash
  tags:
    - volume

- name: Ensure mount point for storage volume exists and has correct permissions
  become: yes
  file:
    path={{ volume_mountpoint }}
    owner={{ volume_user }}
    group={{ volume_group }}
    state=directory
  tags:
    - volume

- name: Mount storage volume
  become: yes
  mount:
    name={{ volume_mountpoint }}
    fstype={{ volume_fstype }}
    passno=0
    src={{ volume_device[provider] }}
    state=mounted
    # opts={{ item.mount_options }}
  tags:
    - volume
