---
# Playbook for creating a virtual machine instance on OpenStack (OS).
#
# Requires the following environment variables:
#  - OS_AUTH_URL
#  - OS_USERNAME
#  - OS_PASSWORD
#  - OS_PROJECT_NAME
- name: "{{ (instance_state == 'present') | ternary('Create','Remove') }} instance"
  local_action: os_server
  args:
    name: "{{ instance_name }}"
    state: "{{ instance_state }}"
    key_name: "{{ key_name }}"
    security_groups: "{{ security_groups }}"
    image: "{{ image }}"
    flavor: "{{ flavor }}"
    auto_ip: yes
    wait: yes
    timeout: 300
    boot_from_volume: yes
    volume_size: "{{ disk_size }}"
    terminate_volume: yes
    network: "{{ network }}"
    region_name: "{{ region }}"
  register: instance

- name: Register IP address of created instance
  set_fact:
    instance_public_ip: "{{ instance.openstack.public_v4 }}"

- name: "{{ (instance_state == 'present') | ternary('Create','Remove') }} storage volume"
  local_action: os_volume
  args:
    display_name: "{{ volume_name }}"
    state: "{{ instance_state }}"
    volume_type: default
    wait: yes
    timeout: 300
    size: "{{ volume_size }}"
    region_name: "{{ region }}"
  register: volume
  when: volume_size is defined

- name: Attach storage volume to instance
  local_action: os_server_volume
  args:
    state: "{{ instance_state }}"
    server: "{{ instance_name }}"
    volume: "{{ volume_name }}"
    device: "{{ volume_device[provider] }}"
    wait: yes
    timeout: 300
  when: (volume_size is defined) and (instance_state == 'present')

