---
# Playbook for creating a virtual machine instance on Gooble Compute Engine (GCE).
#
# Requires the following environment variables to be set:
#  - GCE_EMAIL
#  - GCE_PROJECT
#  - GCE_CREDENTIALS_FILE_PATH: path to an credentials file in JSON format
#    (https://developers.google.com/identity/protocols/application-default-credentials)
- name: Create boot disk
  delegate_to: localhost
  gce_pd:
    disk_type: pd-standard
    image: "{{ image }}"
    name: "{{ instance_name }}"
    size_gb: "{{ disk_size }}"
    zone: "{{ region }}"

- name: "{{ (instance_state == 'present') | ternary('Create','Remove') }} instance"
  vars:
    ssh_key: "{{ lookup('file', key_file) }}"
  delegate_to: localhost
  gce:
    state: "{{ instance_state }}"
    name: "{{ instance_name }}"
    image: "{{ image }}"
    machine_type: "{{ flavor }}"
    external_ip: ephemeral
    network: "{{ network }}"
    zone: "{{ region }}"
    disks:
      - name: "{{ instance_name }}"
        mode: READ_WRITE
    metadata:
      ssh-keys: "ubuntu:{{ ssh_key }}"
    disk_auto_delete: yes
  register: instance

- name: Register IP address of created instance
  set_fact:
    instance_public_ip: "{{ instance.instance_data[0].public_ip }}"
  when: instance_state == 'present'

- name: "{{ (instance_state == 'present') | ternary('Create','Remove') }} storage volume and attach it to instance"
  delegate_to: localhost
  gce_pd:
    state: "{{ instance_state }}"
    zone: "{{ region }}"
    name: "{{ volume_name }}"
    instance_name: "{{ instance_name }}"
    size_gb: "{{ volume_size }}"
    mode: READ_WRITE
  when: volume_size is defined
